const styleList = [
  {
    key: "default",
    buildIn: true,
    label: "default",
    description: "内置皮肤default",
    icon: "📄",
  },
  {
    key: "orangeheart",
    buildIn: true,
    label: "orangeHeart",
    description: "内置皮肤orangeHeart",

    icon: "🧡",
  },
  {
    key: "rainbow",
    buildIn: true,
    label: "rainbow",
    description: "内置皮肤rainbow",

    icon: "🌈",
  },
  {
    key: "lapis",
    buildIn: true,
    label: "lapis",
    description: "内置皮肤lapis",

    icon: "💎",
  },
  {
    key: "pie",
    buildIn: true,
    label: "pie",
    description: "默认皮肤pie",

    icon: "🥧",
  },
  {
    key: "maize",
    buildIn: true,
    label: "maize",
    description: "默认皮肤maize",

    icon: "🌽",
  },
  {
    key: "purple",
    buildIn: true,
    label: "purple",
    description: "默认皮肤purple",
    icon: "💜",
  },
  {
    key: "phycat",
    buildIn: true,
    label: "phyCat",
    description: "默认皮肤phycat",

    icon: "🐱",
  },
  //diy
  {
    key: "arcade",
    file: "style-arcade",
    description: "街机游戏风",
    preview: "/wechatTemplate/image.png",
  },
  {
    key: "artdeco",
    file: "style-artdeco",
    description: "Art Deco 装饰艺术风",
    preview: "/preview/themes/artdeco.png",
  },
  {
    key: "blueprint",
    file: "style-blueprint",
    description: "工程蓝图风",
    preview: "/preview/themes/blueprint.png",
  },
  {
    key: "brutalist",
    file: "style-brutalist",
    description: "极简粗野主义",
    preview: "/preview/themes/brutalist.png",
  },
  {
    key: "carbon",
    file: "style-carbon",
    description: "碳灰终端风",
    preview: "/preview/themes/carbon.png",
  },
  {
    key: "catppuccin",
    file: "style-catppuccin",
    description: "Catppuccin 柔和色调",
    preview: "/preview/themes/catppuccin.png",
  },
  {
    key: "cyberpunk",
    file: "style-cyberpunk",
    description: "赛博朋克",
    preview: "/preview/themes/cyberpunk.png",
  },
  {
    key: "editorial",
    file: "style-editorial",
    description: "杂志编辑风",
    preview: "/preview/themes/editorial.png",
  },
  {
    key: "flat",
    file: "style-flat",
    description: "扁平简约风",
    preview: "/preview/themes/flat.png",
  },
  {
    key: "forest",
    file: "style-forest",
    description: "森林自然风",
    preview: "/preview/themes/forest.png",
  },
  {
    key: "gray",
    file: "style-gray",
    description: "高级灰",
    preview: "/preview/themes/gray.png",
  },
  {
    key: "hacker",
    file: "style-hacker",
    description: "黑客终端风",
    preview: "/preview/themes/hacker.png",
  },
  {
    key: "indigo",
    file: "style-indigo",
    description: "靛蓝暗色系",
    preview: "/preview/themes/indigo.png",
  },
  {
    key: "indigo2",
    file: "style-indigo2",
    description: "靛蓝渐变",
    preview: "/preview/themes/indigo2.png",
  },
  {
    key: "memphis",
    file: "style-memphis",
    description: "孟菲斯设计风",
    preview: "/preview/themes/memphis.png",
  },
  {
    key: "minimal",
    file: "style-minimal",
    description: "清新简约风",
    preview: "/preview/themes/minimal.png",
  },
  {
    key: "mist",
    file: "style-mist",
    description: "薄雾淡雅风",
    preview: "/preview/themes/mist.png",
  },
  {
    key: "neon",
    file: "style-neon",
    description: "霓虹渐变风",
    preview: "/preview/themes/neon.png",
  },
  {
    key: "neutral",
    file: "style-neutral",
    description: "中性灰暗色",
    preview: "/preview/themes/neutral.png",
  },
  {
    key: "newspaper",
    file: "style-newspaper",
    description: "报纸复古风",
    preview: "/preview/themes/newspaper.png",
  },
  {
    key: "ocean",
    file: "style-ocean",
    description: "海洋蓝暗色系",
    preview: "/preview/themes/ocean.png",
  },
  {
    key: "orange",
    file: "style-orange",
    description: "橙色暗色系",
    preview: "/preview/themes/orange.png",
  },
  {
    key: "paper",
    file: "style-paper",
    description: "纸张留白风",
    preview: "/preview/themes/paper.png",
  },
  {
    key: "pink",
    file: "style-pink",
    description: "粉色暗色系",
    preview: "/preview/themes/pink.png",
  },
  {
    key: "pink2",
    file: "style-pink2",
    description: "粉色亮色系",
    preview: "/preview/themes/pink2.png",
  },
  {
    key: "postit",
    file: "style-postit",
    description: "便利贴手绘风",
    preview: "/preview/themes/postit.png",
  },
  {
    key: "purple",
    file: "style-purple",
    description: "紫色亮色系",
    preview: "/preview/themes/purple.png",
  },
  {
    key: "red",
    file: "style-red",
    description: "红色亮色系",
    preview: "/preview/themes/red.png",
  },
  {
    key: "sky",
    file: "style-sky",
    description: "天空蓝亮色系",
    preview: "/preview/themes/sky.png",
  },
  {
    key: "slate",
    file: "style-slate",
    description: "石板灰暗色系",
    preview: "/preview/themes/slate.png",
  },
  {
    key: "slate2",
    file: "style-slate2",
    description: "石板灰亮色系",
    preview: "/preview/themes/slate2.png",
  },
  {
    key: "steampunk",
    file: "style-steampunk",
    description: "蒸汽朋克",
    preview: "/preview/themes/steampunk.png",
  },
  {
    key: "stone",
    file: "style-stone",
    description: "石头暖暗色系",
    preview: "/preview/themes/stone.png",
  },
  {
    key: "swiss",
    file: "style-swiss",
    description: "瑞士极简风",
    preview: "/preview/themes/swiss.png",
  },
  {
    key: "teal",
    file: "style-teal",
    description: "青绿亮色系",
    preview: "/preview/themes/teal.png",
  },
  {
    key: "teal2",
    file: "style-teal2",
    description: "青绿暗色系",
    preview: "/preview/themes/teal2.png",
  },
  {
    key: "vaporwave",
    file: "style-vaporwave",
    description: "蒸汽波",
    preview: "/preview/themes/vaporwave.png",
  },
  {
    key: "vintage",
    file: "style-vintage",
    description: "复古报纸风",
    preview: "/preview/themes/vintage.png",
  },
  {
    key: "violet",
    file: "style-violet",
    description: "紫罗兰亮色系",
    preview: "/preview/themes/violet.png",
  },
  {
    key: "wildwest",
    file: "style-wildwest",
    description: "狂野西部风",
    preview: "/preview/themes/wildwest.png",
  },
  {
    key: "yellow",
    file: "style-yellow",
    description: "明黄亮色系",
    preview: "/preview/themes/yellow.png",
  },
  {
    key: "zinc",
    file: "style-zinc",
    description: "锌灰暗色系",
    preview: "/preview/themes/zinc.png",
  },
];

export default styleList;
