const styleList = [
  { name: "default", file: "default.css", description: "漫画风格（默认）" },
  { name: "arcade", file: "style-arcade.css", description: "街机游戏风" },
  {
    name: "artdeco",
    file: "style-artdeco.css",
    description: "Art Deco 装饰艺术风",
  },
  { name: "blueprint", file: "style-blueprint.css", description: "工程蓝图风" },
  {
    name: "brutalist",
    file: "style-brutalist.css",
    description: "极简粗野主义",
  },
  { name: "carbon", file: "style-carbon.css", description: "碳灰终端风" },
  {
    name: "catppuccin",
    file: "style-catppuccin.css",
    description: "Catppuccin 柔和色调",
  },
  { name: "cyberpunk", file: "style-cyberpunk.css", description: "赛博朋克" },
  { name: "editorial", file: "style-editorial.css", description: "杂志编辑风" },
  { name: "flat", file: "style-flat.css", description: "扁平简约风" },
  { name: "forest", file: "style-forest.css", description: "森林自然风" },
  { name: "gray", file: "style-gray.css", description: "高级灰" },
  { name: "hacker", file: "style-hacker.css", description: "黑客终端风" },
  { name: "indigo", file: "style-indigo.css", description: "靛蓝暗色系" },
  { name: "indigo2", file: "style-indigo2.css", description: "靛蓝渐变" },
  { name: "memphis", file: "style-memphis.css", description: "孟菲斯设计风" },
  { name: "minimal", file: "style-minimal.css", description: "清新简约风" },
  { name: "mist", file: "style-mist.css", description: "薄雾淡雅风" },
  { name: "neon", file: "style-neon.css", description: "霓虹渐变风" },
  { name: "neutral", file: "style-neutral.css", description: "中性灰暗色" },
  { name: "newspaper", file: "style-newspaper.css", description: "报纸复古风" },
  { name: "ocean", file: "style-ocean.css", description: "海洋蓝暗色系" },
  { name: "orange", file: "style-orange.css", description: "橙色暗色系" },
  { name: "paper", file: "style-paper.css", description: "纸张留白风" },
  { name: "pink", file: "style-pink.css", description: "粉色暗色系" },
  { name: "pink2", file: "style-pink2.css", description: "粉色亮色系" },
  { name: "postit", file: "style-postit.css", description: "便利贴手绘风" },
  { name: "purple", file: "style-purple.css", description: "紫色亮色系" },
  { name: "red", file: "style-red.css", description: "红色亮色系" },
  { name: "sky", file: "style-sky.css", description: "天空蓝亮色系" },
  { name: "slate", file: "style-slate.css", description: "石板灰暗色系" },
  { name: "slate2", file: "style-slate2.css", description: "石板灰亮色系" },
  { name: "steampunk", file: "style-steampunk.css", description: "蒸汽朋克" },
  { name: "stone", file: "style-stone.css", description: "石头暖暗色系" },
  { name: "swiss", file: "style-swiss.css", description: "瑞士极简风" },
  { name: "teal", file: "style-teal.css", description: "青绿亮色系" },
  { name: "teal2", file: "style-teal2.css", description: "青绿暗色系" },
  { name: "vaporwave", file: "style-vaporwave.css", description: "蒸汽波" },
  { name: "vintage", file: "style-vintage.css", description: "复古报纸风" },
  { name: "violet", file: "style-violet.css", description: "紫罗兰亮色系" },
  { name: "wildwest", file: "style-wildwest.css", description: "狂野西部风" },
  { name: "yellow", file: "style-yellow.css", description: "明黄亮色系" },
  { name: "zinc", file: "style-zinc.css", description: "锌灰暗色系" },
];

export default styleList;
